# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1351, 864)
        Form.setStyleSheet("QMainWindow {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"QLabel {\n"
"    color: #dcdcdc;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #3c3f41;\n"
"    color: #ffffff;\n"
"    gridline-color: #555555;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #323232;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #365880;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4a76a8;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #3c3f41;\n"
"    color: white;\n"
"    border: 1px solid #555555;\n"
"    padding: 4px;\n"
"}\n"
"QProgressBar {\n"
"    border: 2px solid #555555;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: white;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 20, 1131, 101))
        self.widget.setObjectName("widget")
        self.txt_path = QtWidgets.QLineEdit(parent=self.widget)
        self.txt_path.setGeometry(QtCore.QRect(10, 10, 1111, 32))
        self.txt_path.setReadOnly(True)
        self.txt_path.setObjectName("txt_path")
        self.btn_browse = QtWidgets.QPushButton(parent=self.widget)
        self.btn_browse.setGeometry(QtCore.QRect(10, 60, 101, 34))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_browse.setIcon(icon)
        self.btn_browse.setObjectName("btn_browse")
        self.btn_start = QtWidgets.QPushButton(parent=self.widget)
        self.btn_start.setGeometry(QtCore.QRect(140, 60, 131, 34))
        font = QtGui.QFont()
        font.setBold(True)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.progressBar = QtWidgets.QProgressBar(parent=Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 140, 1111, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lbl_status = QtWidgets.QLabel(parent=Form)
        self.lbl_status.setGeometry(QtCore.QRect(20, 170, 1111, 18))
        self.lbl_status.setObjectName("lbl_status")
        self.tbl_results = QtWidgets.QTableWidget(parent=Form)
        self.tbl_results.setGeometry(QtCore.QRect(20, 200, 1111, 531))
        self.tbl_results.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tbl_results.setAlternatingRowColors(False)
        self.tbl_results.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.tbl_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tbl_results.setObjectName("tbl_results")
        self.tbl_results.setColumnCount(4)
        self.tbl_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_results.setHorizontalHeaderItem(3, item)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setGeometry(QtCore.QRect(10, 740, 1121, 91))
        self.widget_2.setObjectName("widget_2")
        self.lbl_stats = QtWidgets.QLabel(parent=self.widget_2)
        self.lbl_stats.setGeometry(QtCore.QRect(10, 10, 1111, 18))
        self.lbl_stats.setObjectName("lbl_stats")
        self.btn_delete = QtWidgets.QPushButton(parent=self.widget_2)
        self.btn_delete.setGeometry(QtCore.QRect(150, 40, 101, 34))
        font = QtGui.QFont()
        font.setBold(True)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_hash = QtWidgets.QPushButton(parent=self.widget_2)
        self.btn_hash.setGeometry(QtCore.QRect(10, 40, 111, 34))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("slack1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_hash.setIcon(icon1)
        self.btn_hash.setCheckable(True)
        self.btn_hash.setObjectName("btn_hash")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.txt_path.setPlaceholderText(_translate("Form", "Taranacak klasörü seçiniz"))
        self.btn_browse.setText(_translate("Form", "Klasör seç"))
        self.btn_start.setText(_translate("Form", "Taramayı başlat"))
        self.lbl_status.setText(_translate("Form", "Hazır bekliyor..."))
        item = self.tbl_results.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Dosya Adı"))
        item = self.tbl_results.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Konum"))
        item = self.tbl_results.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Boyut"))
        item = self.tbl_results.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Hash"))
        self.lbl_stats.setText(_translate("Form", "0 dosya tarandı. 0 kopya bulundu."))
        self.btn_delete.setText(_translate("Form", "Seçilenleri sil!"))
        self.btn_hash.setText(_translate("Form", "Hash Göster"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
